# Generated by Django 4.0.5 on 2022-06-11 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchDataTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchid', models.IntegerField()),
                ('playerid', models.CharField(max_length=20)),
                ('fighter', models.CharField(max_length=20)),
                ('playerrank', models.IntegerField()),
                ('kills', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('selfdestructs', models.IntegerField()),
                ('damagegiven', models.IntegerField()),
                ('damagetaken', models.IntegerField()),
                ('stagename', models.CharField(max_length=50)),
                ('matchdate', models.DateField()),
            ],
        ),
    ]
