# Generated by Django 4.0.5 on 2022-06-11 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stattracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matchdatatest',
            unique_together={('matchid', 'playerid')},
        ),
    ]
