# Generated by Django 4.0.5 on 2022-06-11 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stattracker', '0002_alter_matchdatatest_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerid', models.CharField(max_length=20)),
                ('collectiondate', models.DateField()),
                ('totalkills', models.IntegerField()),
                ('avgkills', models.DecimalField(decimal_places=2, max_digits=3)),
                ('totaldeaths', models.IntegerField()),
                ('avgdeaths', models.DecimalField(decimal_places=2, max_digits=3)),
                ('totalsds', models.IntegerField()),
                ('avgsds', models.DecimalField(decimal_places=2, max_digits=3)),
                ('totalwins', models.IntegerField()),
                ('kdratio', models.DecimalField(decimal_places=2, max_digits=3)),
                ('avgrank', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
            options={
                'unique_together': {('playerid', 'collectiondate')},
            },
        ),
    ]
