# Generated by Django 4.0.5 on 2022-06-11 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stattracker', '0003_playerstats'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlayerStats',
            new_name='PlayerStatsTest',
        ),
    ]
