# Generated by Django 4.0.5 on 2022-06-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stattracker', '0004_rename_playerstats_playerstatstest'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstatstest',
            name='avgdmggiven',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='playerstatstest',
            name='avgdmgtaken',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='playerstatstest',
            name='totaldmggiven',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='playerstatstest',
            name='totaldmgtaken',
            field=models.IntegerField(null=True),
        ),
    ]
