# Generated by Django 4.0.5 on 2022-06-12 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stattracker', '0007_alter_playerstatstest_avgdmggiven_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchid', models.IntegerField()),
                ('playerid', models.CharField(max_length=20)),
                ('fighter', models.CharField(max_length=20)),
                ('playerrank', models.IntegerField()),
                ('kills', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('selfdestructs', models.IntegerField()),
                ('damagegiven', models.IntegerField(null=True)),
                ('damagetaken', models.IntegerField(null=True)),
                ('stagename', models.CharField(blank=True, max_length=50)),
                ('matchdate', models.DateField()),
            ],
            options={
                'unique_together': {('matchid', 'playerid')},
            },
        ),
        migrations.RenameModel(
            old_name='PlayerStatsTest',
            new_name='PlayerStats',
        ),
        migrations.DeleteModel(
            name='MatchDataTest',
        ),
    ]
